Setup actions and prehooks dc 03
droidcovenhq/droidcovenapp pull request #1
Opened 2022-10-22 09:00 UTC by droidcoven

Setting up Actions and Prehooks

2022-10-22 14:00 UTC, VictorOluwaseun submitted a review, later dismissed

2022-10-23 16:54 UTC, Olamicode requested changes
Is there no way we can add this gradle.xml  and vcs.xml in .idea folder to gitignore so that we don't push it to git? Cos I don't think it's a good idea to push to git as I believe this changes depending on different machines and android versions and create merge conflicts. Check [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) for more context.

2022-10-23 17:25 UTC, VictorOluwaseun approved these changes

2022-10-23 20:37 UTC, Olamicode approved these changes

2022-10-23 21:24 UTC, VictorOluwaseun approved these changes

2022-10-23 21:48 UTC, kolanse approved these changes

2022-10-24 05:50 UTC, merged